//redux
import { useSelector, useDispatch } from "react-redux";
// Head
import Head from "next/head";
// Styles
import styles from "../../styles/Cart.module.css";
// Others
import { deleteItemFromCart } from "../../redux/cartSlice";
import { fotmatMoney, calculateTotal } from "../../function/utils";
import { useState } from "react";
import Noty from "noty";
import Modal from "./../../components/Modal/Modal";

const Cart = () => {
  const [displayModal, setDisplayModal] = useState(false);
  const { cartItems } = useSelector((state) => state.cart);
  const { userInfo } = useSelector((state) => state.auth);
  const dispatch = useDispatch();

  const handleDeleteItem = (id) => {
    dispatch(deleteItemFromCart(id));
    return;
  }
 const handleConfirm = () => {
    if (userInfo?.auth) {
      setDisplayModal(true);
      return;
    } else {
      new Noty({
        type: "error",
        timeout: 1500,
        text: "Vui lòng đăng nhập để tiếp tục",
        progressBar: true,
      }).show();
      return;
    }
  };

  return (
    <div>
      <Head>
        <title>Giỏ hàng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Modal
          auth={userInfo?.auth}
          cartItems={cartItems}
          setDisplayModal={setDisplayModal}
          displayModal={displayModal}
        />
        <div className={styles.cart}>
          <h1 className={styles.title}>
            Có {cartItems ? cartItems?.length : 0} sản phẩm trong giỏ hàng
          </h1>
          <div className={styles.items}>
            {cartItems && cartItems?.length > 0 ?
              cartItems.map((ite, i) => (
                <div key={i} className={styles.item}>
                  <img src={`${ite.image}`} alt="img" />
                  <div className={styles.text}>
                    <span className={styles.name}>{ite.name}</span>
                    <span className={styles.desc}>{ite.description}</span>
                  </div>
                  <div className={styles.total}>
                    <i
                      onClick={() => handleDeleteItem(ite._id)}
                      className="fa-solid fa-trash"
                    ></i>
                    <div className={styles.btnx}>
                      <span className={styles.amount}>Số lượng: {ite.qty}</span>
                      <span className={styles.prices}>
                        {fotmatMoney(ite.qty * ite.price)}
                      </span>
                    </div>
                  </div>
                </div>
              ))
              : (
                <div className="imageCart">
                  <img style={{width: '400px'}} src="/empty-cart.png" alt="" />
                </div>
              )
              }
          </div>

          {cartItems && cartItems?.length > 0 && (
            <>
              <div className={styles.totalMoney}>
                <h2>
                  Tổng thiệt hại: {fotmatMoney(calculateTotal(cartItems))}
                </h2>
              </div>
              <button onClick={handleConfirm} className={styles.buy}>
                Mua hàng
              </button>
            </>
          )}
        </div>
      </>
    </div>
  );
};

export default Cart;
