import styles from "../../styles/ThongKe.module.css";
import User from "../../components/User";
import Warehouse from "../../components/Warehouse";
import { useState, useEffect } from "react";
import Head from "next/head";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import AddProduct from "../../components/AddProduct";


const ThongKe = () => {
  const [active, setActive] = useState(1);
  const { userInfo } = useSelector((state) => state.auth);
  const router = useRouter();

  useEffect(() => {
    if (!userInfo?.user.isAdmin) {
      component = null;
      router.replace("/");
    }
  }, [userInfo]);

  let component;
  switch (active) {
    case 1:
      component = <User />;
      break;
    case 2:
      component = <AddProduct />;
      break;
    case 3:
      component = <Warehouse />;
      break;
    default:
      component = <User />;
      return;
  }
  return (
    <div className={styles.thongke}>
      <Head>
        <title>Thống kê</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navLeft}>
        <ul className={styles.menu_admin}>
          <li onClick={() => setActive(1)}>
            <i className="fa-solid fa-users"></i>
            <a>Người dùng</a>
          </li>
          <li onClick={() => setActive(3)}>
            <i class="fa-solid fa-warehouse"></i>
            <a>Kho hàng</a>
          </li>
          <li onClick={() => setActive(2)}>
            <i class="fa-solid fa-plus"></i>
            <a>Thêm sản phẩm</a>
          </li>
        </ul>
      </div>
      <div className={styles.navright}>{component}</div>
    </div>
  );
};

export default ThongKe;
