import { useState, useEffect } from "react"
import { useSelector } from "react-redux";
// styles
import styles from "../../styles/Products.module.css"
// next modules
import Head from "next/head"
//redux
import { useDispatch } from "react-redux"
// others
import { addToCart } from "../../redux/cartSlice"
import {fotmatMoney} from '../../function/utils'
// packaget
import Noty from "noty";
import apiModule from "../../http"
import Comment from "../../components/Comment"
import { useRouter } from "next/router"
const { getProductById, getallProducts } = apiModule()

export const getStaticPaths = async () => {
  const getPath = await getallProducts({page:999, size:999})
  const paths = getPath.data.map((path) => {
    return {
      params: { id: path._id.toString() },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {

  const res = await getProductById(context.params.id)
  const product = res.data;
  return {
    props: {
      product,
    },
  }
}

const Details = ({ product }) => {
  const dispatch = useDispatch();
  const [qty, setQty] = useState(0);
  const router = useRouter()
  const {id} = router.query
  
  const handleAddToCart = () => {
    dispatch(addToCart({ qty, ...product }));
    new Noty({
      type: "success",
      timeout: 1000,
      text: "Thêm vào giỏ hàng thành công",
      progressBar: false,
    }).show();
    return;
  }
  const {userInfo} = useSelector((state) => state.auth)
  useEffect(() => {
    if(userInfo?.user.isAdmin) {
      router.replace('/')
    }
  }, [userInfo])
  return (
    <>
      <Head>
        <title>Chi tiết sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.details}>
        <div className={styles.left}>
          <img src={`${product.image}`} alt="img" />
        </div>
        <div className={styles.right}>
          <h1 className={styles.title}><i class="fa-solid fa-align-right"></i> {product.name}</h1>
          <p className={styles.sold}>{product.countInStock === 0 ? "Đã hết hàng" : `Đã bán: ${product.sold} | Còn: ${product.countInStock}`}</p>
          <button className={styles.price}>Giá: {fotmatMoney(product.price)}</button>
          <h4 className={styles.desc}><i class="fa-solid fa-angles-right"></i> {product.description}</h4>
          <div className={styles.options}>
            <div className={styles.amount}>

              <div>
                <button disabled={product.countInStock === 0} onClick={() => setQty((prev) => prev + 1)}>+</button>
                <input
                disabled={product.countInStock === 0}
                  value={qty}
                  type="number"
                  onChange={(e) => setQty(+e.target.value)}
                />
                <button
                disabled={product.countInStock === 0}
                  onClick={() => {
                    qty > 0 && setQty((prev) => prev - 1);
                  }}
                >
                  -
                </button>
              </div>
            </div>
            <div className={styles.addcart}>
                <button className="okmfg" disabled={qty === 0} onClick={handleAddToCart}>Thêm vào giỏ</button>
            </div>
          </div>
        </div>
      </div>
      <Comment id={id}/>
    </>
  );
};

export default Details;
