import { useState, useEffect } from "react";
// next modules
import { useRouter } from "next/router";
import Head from "next/head";
// package
import Noty from "noty";
// redux
import { useDispatch, useSelector } from "react-redux";
// others
import { login,logout } from "../../redux/authSlice";
import { resetMessage } from "../../redux/authSlice";

const Login = () => {
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  const dispatch = useDispatch();
  const { userInfo, error, loading } = useSelector((state) => state.auth)

  const router = useRouter();

  useEffect(() => {
    if (userInfo?.auth && !userInfo?.user?.block) {
      router.replace("/");
    }
  }, [userInfo?.auth, !userInfo?.user?.block])

  useEffect(() => {
    if (userInfo?.user?.block) {
      new Noty({
        type: "error",
        timeout: 1500,
        text: 'Tài khoản đã bị khóa',
        progressBar: true,
      }).show();
      dispatch(logout())
    }
  }, [userInfo, dispatch])

  const handleLogin = (e) => {
    e.preventDefault();
    if (!password || !email) {
      new Noty({
        type: "error",
        timeout: 1500,
        text: "Không được bỏ trống mục nào",
        progressBar: true,
      }).show();
      return;
    }
    dispatch(login({ email, password }))
  }

  useEffect(() => {
    if (error) {
      new Noty({
        type: "error",
        timeout: 1500,
        text: `${error}`,
        progressBar: true,
      }).show();
      dispatch(resetMessage());
      return;
    }
  }, [error]);

  return (
    <>
      <Head>
        <title>Đăng nhập</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="form_auth">
        <div className="form-style-3">
          <form onSubmit={handleLogin}>
            <fieldset>
              <legend>Đăng nhập</legend>
              <label for="field2">
                <span>
                  Email <span className="required">*</span>
                </span>
                <input
                  onChange={(e) => setEmail(e.target.value)}
                  value={email}
                  type="email"
                  class="input-field"
                  name="field2"
                />
              </label>
              <label for="field3">
                <span>
                  Mật khẩu <span className="required">*</span>
                </span>
                <input
                  onChange={(e) => setPassword(e.target.value)}
                  value={password}
                  type="password"
                  class="input-field"
                  name="field3"
                />
              </label>
            </fieldset>
            <fieldset>
              <input
                type="submit"
                value={loading ? "Xin chờ..." : `Đăng nhập`}
              />
            </fieldset>
          </form>
          
        </div>
      </div>
    </>
  );
};

export default Login;
